### ISSUE TITLE
This plugin works perfect for the provided methods but i need more 

### ISSUE THREAD

**Issue by aliuadepoju** [rampicos/Cordova-SMS-Plugin#1]
Please can the author include DELETE method and unique ID for the incoming SMS?

**Comment by aliuadepoju** [comment]
I have a quick question, does SMS message get deleted immediately received?

CordovaSMS.onSMS(function(sms){
    alert('Message is '+JSON.stringify(sms));
  });

**Comment by rampicos** [comment]
Thanks for your comment. You have to push the SMS to your local storage like SQLite for the future use. Nature of SMS is to broadcasted, so the app has to store it to the local DB and all SMS apps usually do that. Hope you can write your own DB and store the require data. If you still require Delete functionality let me know

**Comment by aliuadepoju** [comment]
Thanks, i ended up storing its on SQLite, it's now perfect. The app can now manage the SMS on local storage and pushes its to an API at a specified time interval

**Comment by rampicos** [comment]
Thanks

**Comment by ademcalhann** [comment]
merhaba ben eklentiyi kullanmadım sms gönderemedim  CordovaSMS.sendSMS(telefon,mesajx,successCallback,errorCallback); bunun haricinde yapmam gerekenler neler  ??
